apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }} 
  name: adria-common-properties-secret
type: Opaque
data:
{{- $env := .Files.Get .Values.envFile }}
{{- range $line := splitList "\n" $env }}
{{- $pair := splitList "=" $line }}
{{- if eq (len $pair) 2 }}
  {{ index $pair 0 | trim }}: {{ index $pair 1 | trim | b64enc }}
{{- end }}
{{- end }}